[cursor]
style = "Underline"
unfocused_hollow = false

[env]
TERM = "xterm-256color"

[font]
size = 8.0

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[scrolling]
history = 100000

[terminal.shell]
args = ["--login"]
program = "/bin/bash"

[window]
dynamic_title = true
opacity = 1
startup_mode = "Windowed"

[window.dimensions]
columns = 120
lines = 30

[window.padding]
x = 2
y = 2
